FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG PROJECT_PATH
WORKDIR /src

COPY . .

RUN dotnet restore "$PROJECT_PATH"
RUN dotnet publish "$PROJECT_PATH" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
ARG PROJECT_DLL
WORKDIR /app

COPY --from=build /app/publish .

ENV PROJECT_DLL=${PROJECT_DLL}

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT ["sh", "-c", "dotnet \"$PROJECT_DLL\""]
